# Generated by Django 5.1 on 2024-08-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='non- library staff', max_length=20),
        ),
    ]
