# Generated by Django 5.1 on 2024-08-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Year_Released', models.DateField(auto_now=True)),
                ('Edition', models.CharField(max_length=10)),
                ('Shelf_Number', models.CharField(max_length=10)),
                ('Number_of_Copies', models.DecimalField(decimal_places=1, max_digits=100)),
            ],
        ),
    ]
