# Generated by Django 5.1 on 2024-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_year_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Year_Released',
            field=models.DateTimeField(),
        ),
    ]
