# Generated by Django 5.1 on 2024-08-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_year_released'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE books_book
            ALTER COLUMN "Year_Released" TYPE VARCHAR(4)
            USING TO_CHAR("Year_Released", 'YYYY');
            """,
            reverse_sql="""
            ALTER TABLE books_book
            ALTER COLUMN "Year_Released" TYPE TIMESTAMP WITH TIME ZONE
            USING "Year_Released"::timestamp with time zone;
            """
        ),
        migrations.AlterField(
            model_name='book',
            name='Year_Released',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]