# Generated by Django 5.1 on 2024-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_year_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Category',
            field=models.CharField(default='Science', max_length=100),
        ),
    ]
