# Generated by Django 5.1 on 2024-08-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Year_Released',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
