# Generated by Django 5.1 on 2024-08-26 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_borrowed_books'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrowed_Books',
            new_name='Borrowed_Book',
        ),
    ]
