# Generated by Django 5.1 on 2024-08-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_borrowed_books_borrowed_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_book',
            name='Overdue',
            field=models.BooleanField(default=False),
        ),
    ]
