# Generated by Django 5.1 on 2024-08-28 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_borrowed_book_overdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed_book',
            name='Book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
