# Generated by Django 5.1 on 2024-08-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_borrowed_book_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed_book',
            name='User',
        ),
    ]
