# Generated by Django 5.1 on 2024-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_borrowed_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Shelf_Number',
            field=models.CharField(max_length=20),
        ),
    ]
