# Generated by Django 5.1 on 2024-09-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_shelf_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Year_Released',
            field=models.IntegerField(),
        ),
    ]
