# Generated by Django 5.1 on 2024-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_year_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Category',
            field=models.CharField(choices=[('A', 'General Works'), ('B', 'Philosophy, Psychology, Religion'), ('C', 'Auxiliary Sciences of History'), ('D', 'World History and History of Europe, Asia, Africa, Australia, New Zealand, etc.'), ('E', 'History of America'), ('F', 'History of the Americas'), ('G', 'Geography, Anthropology, and Recreation'), ('H', 'Social Sciences'), ('J', 'Political Science'), ('K', 'Law'), ('K', 'Journals and reference books'), ('KA', 'Jurisprudence'), ('KB', 'General and comparative law'), ('KC', 'International law'), ('KD', 'Religious legal systems'), ('KE', 'Ancient and medieval law'), ('KF-KN', 'Common law'), ('KF', 'British Isles'), ('KG', 'Canada, US, West Indies'), ('KH', 'Australia, New Zealand'), ('KL', 'General'), ('KM', 'Public law'), ('KN', 'Private law'), ('KP', 'Preferred jurisdiction'), ('KR', 'Africa'), ('KS', 'Latin America'), ('KT', 'Asia and Pacific'), ('KV', 'Europe'), ('KW', 'European Community Law (alternative)'), ('KZ', 'Non-legal subjects'), ('L', 'Education'), ('M', 'Music'), ('N', 'Fine Arts'), ('P', 'Language and Literature'), ('Q', 'Science'), ('R', 'Medicine'), ('S', 'Agriculture'), ('T', 'Technology'), ('U', 'Military Science'), ('V', 'Naval Science'), ('Z', 'Bibliography, Library Science, and General Information Resources')], default='Science', max_length=100),
        ),
    ]
