# Generated by Django 5.1 on 2024-09-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN_Number',
            field=models.CharField(default='0000000000000', max_length=13, null=True),
        ),
    ]
