# Generated by Django 5.1 on 2024-09-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='staffwriting',
            name='level',
            field=models.CharField(default='100 Level', max_length=200),
        ),
        migrations.AlterField(
            model_name='staffwriting',
            name='department',
            field=models.CharField(default='Software Engineering', max_length=200),
        ),
    ]
