# Generated by Django 5.1 on 2024-09-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_departments_staffwriting_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffwriting',
            name='department',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Computer Science', 'Computer Science'), ('Nursing', 'Nursing')], default='Software Engineering', max_length=200),
        ),
        migrations.AlterField(
            model_name='staffwriting',
            name='level',
            field=models.CharField(choices=[('100 Level', '100 Level'), ('200 Level', '200 Level'), ('300 Level', '300 Level'), ('400 Level', '400 Level')], default='100 Level', max_length=200),
        ),
    ]
